name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to OVH via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cluster105.hosting.ovh.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./
          server-dir: /www/
          dangerous-clean-slate: true